language: objective-c
osx_image: xcode7.3

script: xctool -workspace unnamedcast.xcworkspace -scheme unnamedcastUnitTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.3" test
